#!/usr/bin/env python3
# ABOUTME: Fetches RSS feeds from Medium and Substack
# ABOUTME: Generates data/external_posts.yaml for Hugo

import xml.etree.ElementTree as ET
from datetime import datetime
from urllib.request import urlopen, Request
from urllib.error import URLError
import yaml
import os

FEEDS = {
    "medium": "https://medium.com/@narasimhakarthik/feed",
    "substack": "https://neuraforge.substack.com/feed"
}

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "external_posts.yaml")

# User agent to avoid 403 errors
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
}


def fetch_feed(url):
    """Fetch and parse RSS feed from URL."""
    try:
        req = Request(url, headers=HEADERS)
        with urlopen(req, timeout=30) as response:
            content = response.read()
            return ET.fromstring(content)
    except (URLError, ET.ParseError) as e:
        print(f"Error fetching {url}: {e}")
        return None


def parse_date(date_str):
    """Parse RSS date string to YYYY-MM-DD format."""
    if not date_str:
        return ""
    formats = [
        "%a, %d %b %Y %H:%M:%S %Z",
        "%a, %d %b %Y %H:%M:%S GMT",
        "%a, %d %b %Y %H:%M:%S %z",
    ]
    for fmt in formats:
        try:
            dt = datetime.strptime(date_str.strip(), fmt)
            return dt.strftime("%Y-%m-%d")
        except ValueError:
            continue
    return ""


def clean_cdata(text):
    """Remove CDATA wrapper from text."""
    if not text:
        return ""
    if "<![CDATA[" in text:
        return text.replace("<![CDATA[", "").replace("]]>", "")
    return text


def parse_feed(root, source_name):
    """Parse RSS feed and extract posts."""
    posts = []
    if root is None:
        return posts

    for item in root.findall(".//item"):
        title_el = item.find("title")
        link_el = item.find("link")
        pub_date_el = item.find("pubDate")

        if title_el is not None and link_el is not None:
            title = clean_cdata(title_el.text or "")
            date_str = parse_date(pub_date_el.text if pub_date_el is not None else "")

            posts.append({
                "title": title,
                "url": link_el.text,
                "date": date_str,
                "source": source_name
            })

    return posts


def main():
    """Main function to fetch feeds and generate YAML."""
    print("Fetching RSS feeds...")

    medium_root = fetch_feed(FEEDS["medium"])
    substack_root = fetch_feed(FEEDS["substack"])

    medium_posts = parse_feed(medium_root, "Medium")
    substack_posts = parse_feed(substack_root, "NeuraForge")

    print(f"Found {len(medium_posts)} Medium posts")
    print(f"Found {len(substack_posts)} Substack posts")

    data = {
        "medium": medium_posts,
        "substack": substack_posts
    }

    # Write YAML file
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write("# External blog posts from Medium and Substack\n")
        f.write("# Auto-generated by scripts/fetch_rss.py\n")
        f.write(f"# Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"Written to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
